Update apps-check.yml

diff --git a/.github/workflows/apps-check.yml b/.github/workflows/apps-check.yml
--- a/.github/workflows/apps-check.yml
+++ b/.github/workflows/apps-check.yml
@@ -506,12 +506,43 @@ jobs:
       - name: "Process log results"
         run: |
           mkdir -p results
-          for LogFile in results/ko-*; do
-              echo "$appname" | tee -a results/excluded
-              rm -f "$LogFile"
+          for LogFile in results/out-*; do
+            echo '-----------------------------------------------------------------'
+            echo "$LogFile out"
+            echo '-----------------------------------------------------------------'
+            cat "$LogFile"
+            echo '-----------------------------------------------------------------'
+            echo '-----------------------------------------------------------------'
+            [ -f "$LogFile" ] || continue
+            appname=$(basename "$LogFile" | cut -d'-' -f2-)
+            echo '-----------------------------------------------------------------'
+            echo "$appname"
+            echo '-----------------------------------------------------------------'
+            if [ -z "$size" ]; then
+              size=$(cat "$LogFile" | grep 'size' | cut -d'=' -f2)
+              echo "size is $size"
+            fi
+            if [ -z "$version" ]; then
+              version=$(cat "$LogFile" | grep 'version' | cut -d'=' -f2)
+              echo "version is $version"
+            fi
+            KoFile="results/ko-$appname"
+            if [[ -f "$KoFile" ]]; then
+              echo "$appname" | tee -a failing results/excluded
+              rm -f "$KoFile"
+              cat "$LogFile" | grep -E '(^.*=.*$|^.*----.*$)' >> results/log
+              sort -u results/excluded -o results/excluded
+              sort -u failing -o failing
+              git add results/excluded
+            else
+              cat "$LogFile" | grep -E '(^.*=.*$|^.*----.*$)' >> results/log
+              echo "$appname" >> results/tested
+            fi
+            echo '-----------------------------------------------------------------' >> results/log
+            rm -f "$LogFile"
           done
-          sort -u results/excluded -o results/excluded
-          git add results/excluded
+          sort -u results/tested -o results/tested
+          git add results
 
   second-try:
     name: "Second try"
