Update apps-check.yml

diff --git a/.github/workflows/apps-check.yml b/.github/workflows/apps-check.yml
--- a/.github/workflows/apps-check.yml
+++ b/.github/workflows/apps-check.yml
@@ -1,4 +1,4 @@
-name: "Apps check"
+name: "Apps check v2"
 
 on:
   push:
@@ -445,134 +445,8 @@ jobs:
 
             # Any other result is a failure
             else
+              echo "${{ matrix.file }}" >> "results/ko-${{ matrix.file }}"
               exit 9
-            fi
-          fi
-
-      - name: "${{ matrix.file }} second try"
-        if: failure()
-        working-directory: programs/x86_64
-        run: |
-          set -uo pipefail
-          mkdir -p results
-          echo "Second try" >> $GITHUB_STEP_SUMMARY
-          # Define the content of the script
-          script_content=$(cat ${{ matrix.file }})
-          # Define the pure name of the app
-          pure_arg=$(echo "${{ matrix.file }}" | sed 's/\-appimage$//g' | sed 's:.*/::')
-
-          # Allow installing applications even if the command already exists
-          sed -i '/command -v "$pure_arg"/d; /command already exists/d' /opt/am/modules/install.am
-
-          # Special patches
-          if [ "$pure_arg" = bat-extras ]; then
-            sed -i 's/if ! command/if command/g' "${{ matrix.file }}"
-          fi
-          if [[ "$pure_arg" =~ (node|npm) ]]; then
-            sed -i 's/_check_if_script_installs_a_metapackage || return 1//g' /opt/am/modules/install.am
-          fi
-
-          # Install the application
-
-          if [ "$pure_arg" = suyu ]; then
-
-            echo "This application cannot be installed on github actions" | tee -a results/log-"${{ matrix.file }}"
-            echo "${{ matrix.file }}" >> results/ok-${{ matrix.file }}
-
-          else
-
-            if [[ "$pure_arg" =~ (libreoffice|mpv|wine) ]]; then
-
-              echo 1 | am -i "${{ matrix.file }}" --debug 2>&1 \
-               | tee -a results/log-"${{ matrix.file }}" \
-               || sudo systemctl restart tor.service && echo 1 \
-               | am -i "${{ matrix.file }}" --debug 2>&1 \
-               | tee -a results/log-"${{ matrix.file }}"
-              size=$(cat "results/log-${{ matrix.file }}" | tee /dev/null | grep 'OF DISK SPACE' | cut -d'(' -f2 | cut -d' ' -f1,2)
-              Preversion=$(cat "results/log-${{ matrix.file }}" | tee /dev/null | grep '◆' | tail -1)
-              echo "pre version is $Preversion"
-              version=$(cat "results/log-${{ matrix.file }}" | tee /dev/null | grep '◆' | tail -1 | awk '{print $3}')
-              echo "version is $version"
-              echo "size=${size}" | tee -a results/out-"${{ matrix.file }}"
-              echo "version=${version}" | tee -a results/out-"${{ matrix.file }}"
-
-            elif [[ "$pure_arg" =~ (bat-extras) ]]; then
-              echo 1 | am -i "$pure_arg" --debug 2>&1 \
-               | tee -a results/log-"${{ matrix.file }}" \
-               || sudo systemctl restart tor.service && echo 1 \
-               | am -i "$pure_arg" --debug 2>&1 \
-               | tee -a results/log-"${{ matrix.file }}"
-              size=$(cat "results/log-${{ matrix.file }}" | tee /dev/null | grep 'OF DISK SPACE' | cut -d'(' -f2 | cut -d' ' -f1,2)
-              Preversion=$(cat "results/log-${{ matrix.file }}" | tee /dev/null | grep '◆' | tail -2 | head -1)
-              echo "pre version is $Preversion"
-              version=$(echo "$Preversion" | awk '{print $3}')
-              echo "version is $version"
-              echo "size=${size}" | tee -a results/out-"${{ matrix.file }}"
-              echo "version=${version}" | tee -a results/out-"${{ matrix.file }}"
-            else
-
-              echo y | am -i "${{ matrix.file }}" --debug 2>&1 \
-               | tee -a results/log-"${{ matrix.file }}" \
-               || sudo systemctl restart tor.service && echo y \
-               | am -i "${{ matrix.file }}" --debug 2>&1 \
-               | tee -a results/log-"${{ matrix.file }}"
-              size=$(cat "results/log-${{ matrix.file }}" | tee /dev/null | grep 'OF DISK SPACE' | cut -d'(' -f2 | cut -d' ' -f1,2)
-              Preversion=$(cat "results/log-${{ matrix.file }}" | tee /dev/null | grep '◆' | tail -1)
-              echo "pre version is $Preversion"
-              version=$(cat "results/log-${{ matrix.file }}" | tee /dev/null | grep '◆' | tail -1 | awk '{print $3}')
-              echo "version is $version"
-              echo "size=${size}" | tee -a results/out-"${{ matrix.file }}"
-              echo "version=${version}" | tee -a results/out-"${{ matrix.file }}"
-            fi
-
-            LASTDIR=$(ls -td /opt/* | head -1 | sed 's:.*/::')
-
-            # If an application is blacklisted, ignore it
-            if [ "$LASTDIR" = am ]; then
-              echo "### 💀 ${{ matrix.file }}" >> $GITHUB_STEP_SUMMARY
-              echo "${{ matrix.file }}" >> results/log-${{ matrix.file }}
-              exit 1
-
-            # If the last modified directory contains a file named "remove", check the installed files
-            elif test -f /opt/"$LASTDIR"/remove; then
-
-              printf "\n-------------------------------------------------------------\n\n"
-
-              # Check structure of directories in /opt
-              echo " Structure of the directory in /opt"
-              echo ""
-              ls /opt/"$LASTDIR" | tee -a results/log-"${{ matrix.file }}"
-
-              printf "\n-------------------------------------------------------------\n\n"
-
-              # Check the command in /usr/local/bin
-              echo " Command in \$PATH"
-              echo ""
-              command -v "$pure_arg" | tee -a results/log-"${{ matrix.file }}" || command -v "$LASTDIR" | tee -a results/log-"${{ matrix.file }}" || ls /usr/local/bin | tee -a results/log-"${{ matrix.file }}"
-
-              printf "\n-------------------------------------------------------------\n\n"
-
-              # Check launchers in /usr/local/share/applications
-              echo " Launchers in /usr/local/share/applications" | tee -a results/log-"${{ matrix.file }}"
-              echo ""
-              if test -f /usr/local/share/applications/*AM.desktop 2>/dev/null; then
-                 ls /usr/local/share/applications | grep "AM.desktop$" | tee -a results/log-"${{ matrix.file }}"
-              elif echo "$script_content" | grep -q -- '^./"$APP" --appimage-extract.*./"$APP".desktop$'; then
-                 ls /usr/local/share/applications | grep "AM.desktop$" | tee -a results/log-"${{ matrix.file }}"
-              else
-                 echo "No .desktop file available" | tee -a results/log-"${{ matrix.file }}"
-              fi
-
-              printf "\n-------------------------------------------------------------\n\n"
-
-              # Remove the application
-              am -R "$LASTDIR" && echo "${{ matrix.file }}" >> results/ok-${{ matrix.file }} || echo "${{ matrix.file }}" >> results/log-${{ matrix.file }}
-
-            # Any other result is a failure
-            else
-              echo "### 💀 ${{ matrix.file }}" >> $GITHUB_STEP_SUMMARY
-              echo "${{ matrix.file }}" >> results/ko-${{ matrix.file }}
-              exit 1
             fi
           fi
 
@@ -601,8 +475,8 @@ jobs:
           path: programs/x86_64/results/ok-${{ matrix.file }}
           retention-days: 1
 
-  update-results:
-    name: "results 📰"
+  download-results:
+    name: "get results"
     needs: run-actions
     runs-on: ubuntu-22.04
     if: (always() && github.event.inputs.reset_stats != 'true')
@@ -631,9 +505,184 @@ jobs:
       - name: "Process log results"
         run: |
           mkdir -p results
-          echo '-----------------------------------------------------------------'
-          echo 'No GitHub/AppImage +'
-          echo '-----------------------------------------------------------------'
+          for LogFile in results/ko-*; do
+              echo "$appname" | tee -a results/excluded
+              rm -f "$LogFile"
+          done
+          sort -u results/excluded -o results/excluded
+          git add results/excluded
+
+  second-try:
+    name: "Second try"
+    needs: download-results
+    if: (always() && github.event.inputs.reset_stats != 'true')
+    runs-on: ubuntu-22.04
+    steps:
+      - name: "Checkout"
+        uses: actions/checkout@v4
+
+      - name: "Second try"
+        working-directory: programs/x86_64
+        run: |
+          set -uo pipefail
+          mkdir -p results
+          echo "Second try" >> $GITHUB_STEP_SUMMARY
+          if [ -f results/excluded ]; then
+            for failed in $(cat results/excluded); do
+              # Define the content of the script
+              script_content=$(cat $failed)
+              # Define the pure name of the app
+              pure_arg=$(echo "$failed" | sed 's/\-appimage$//g' | sed 's:.*/::')
+
+              # Allow installing applications even if the command already exists
+              sed -i '/command -v "$pure_arg"/d; /command already exists/d' /opt/am/modules/install.am
+
+              # Special patches
+              if [ "$pure_arg" = bat-extras ]; then
+                  sed -i 's/if ! command/if command/g' "$failed"
+              fi
+              if [[ "$pure_arg" =~ (node|npm) ]]; then
+                  sed -i 's/_check_if_script_installs_a_metapackage || return 1//g' /opt/am/modules/install.am
+              fi
+
+              # Install the application
+
+              if [ "$pure_arg" = suyu ]; then
+
+                  echo "This application cannot be installed on github actions" | tee -a results/log-"$failed"
+                  echo "$failed" >> results/ok-$failed
+
+              else
+
+                  if [[ "$pure_arg" =~ (libreoffice|mpv|wine) ]]; then
+
+                  echo 1 | am -i "$failed" --debug 2>&1 \
+                  | tee -a results/log-"$failed" \
+                  || sudo systemctl restart tor.service && echo 1 \
+                  | am -i "$failed" --debug 2>&1 \
+                  | tee -a results/log-"$failed"
+                  size=$(cat "results/log-$failed" | tee /dev/null | grep 'OF DISK SPACE' | cut -d'(' -f2 | cut -d' ' -f1,2)
+                  Preversion=$(cat "results/log-$failed" | tee /dev/null | grep '◆' | tail -1)
+                  echo "pre version is $Preversion"
+                  version=$(cat "results/log-$failed" | tee /dev/null | grep '◆' | tail -1 | awk '{print $3}')
+                  echo "version is $version"
+                  echo "size=${size}" | tee -a results/out-"$failed"
+                  echo "version=${version}" | tee -a results/out-"$failed"
+
+                  elif [[ "$pure_arg" =~ (bat-extras) ]]; then
+                  echo 1 | am -i "$pure_arg" --debug 2>&1 \
+                  | tee -a results/log-"$failed" \
+                  || sudo systemctl restart tor.service && echo 1 \
+                  | am -i "$pure_arg" --debug 2>&1 \
+                  | tee -a results/log-"$failed"
+                  size=$(cat "results/log-$failed" | tee /dev/null | grep 'OF DISK SPACE' | cut -d'(' -f2 | cut -d' ' -f1,2)
+                  Preversion=$(cat "results/log-$failed" | tee /dev/null | grep '◆' | tail -2 | head -1)
+                  echo "pre version is $Preversion"
+                  version=$(echo "$Preversion" | awk '{print $3}')
+                  echo "version is $version"
+                  echo "size=${size}" | tee -a results/out-"$failed"
+                  echo "version=${version}" | tee -a results/out-"$failed"
+                  else
+
+                  echo y | am -i "$failed" --debug 2>&1 \
+                  | tee -a results/log-"$failed" \
+                  || sudo systemctl restart tor.service && echo y \
+                  | am -i "$failed" --debug 2>&1 \
+                  | tee -a results/log-"$failed"
+                  size=$(cat "results/log-$failed" | tee /dev/null | grep 'OF DISK SPACE' | cut -d'(' -f2 | cut -d' ' -f1,2)
+                  Preversion=$(cat "results/log-$failed" | tee /dev/null | grep '◆' | tail -1)
+                  echo "pre version is $Preversion"
+                  version=$(cat "results/log-$failed" | tee /dev/null | grep '◆' | tail -1 | awk '{print $3}')
+                  echo "version is $version"
+                  echo "size=${size}" | tee -a results/out-"$failed"
+                  echo "version=${version}" | tee -a results/out-"$failed"
+                  fi
+
+                  LASTDIR=$(ls -td /opt/* | head -1 | sed 's:.*/::')
+
+                  # If an application is blacklisted, ignore it
+                  if [ "$LASTDIR" = am ]; then
+                  echo "### 💀 $failed" >> $GITHUB_STEP_SUMMARY
+                  echo "$failed" >> results/log-$failed
+                  exit 1
+
+                  # If the last modified directory contains a file named "remove", check the installed files
+                  elif test -f /opt/"$LASTDIR"/remove; then
+
+                  printf "\n-------------------------------------------------------------\n\n"
+
+                  # Check structure of directories in /opt
+                  echo " Structure of the directory in /opt"
+                  echo ""
+                  ls /opt/"$LASTDIR" | tee -a results/log-"$failed"
+
+                  printf "\n-------------------------------------------------------------\n\n"
+
+                  # Check the command in /usr/local/bin
+                  echo " Command in \$PATH"
+                  echo ""
+                  command -v "$pure_arg" | tee -a results/log-"$failed" || command -v "$LASTDIR" | tee -a results/log-"$failed" || ls /usr/local/bin | tee -a results/log-"$failed"
+
+                  printf "\n-------------------------------------------------------------\n\n"
+
+                  # Check launchers in /usr/local/share/applications
+                  echo " Launchers in /usr/local/share/applications" | tee -a results/log-"$failed"
+                  echo ""
+                  if test -f /usr/local/share/applications/*AM.desktop 2>/dev/null; then
+                      ls /usr/local/share/applications | grep "AM.desktop$" | tee -a results/log-"$failed"
+                  elif echo "$script_content" | grep -q -- '^./"$APP" --appimage-extract.*./"$APP".desktop$'; then
+                      ls /usr/local/share/applications | grep "AM.desktop$" | tee -a results/log-"$failed"
+                  else
+                      echo "No .desktop file available" | tee -a results/log-"$failed"
+                  fi
+
+                  printf "\n-------------------------------------------------------------\n\n"
+
+                  # Remove the application
+                  am -R "$LASTDIR" && echo "$failed" >> results/ok-$failed || echo "$failed" >> results/log-$failed
+
+                  # Any other result is a failure
+                  else
+                  echo "### 💀 $failed" >> $GITHUB_STEP_SUMMARY
+                  echo "$failed" >> results/ko-$failed
+                  exit 1
+                  fi
+              fi
+            done
+          else
+            echo "All OK"
+          fi
+
+  update-results:
+    name: "results 📰"
+    needs: second-try
+    runs-on: ubuntu-22.04
+    if: (always() && github.event.inputs.reset_stats != 'true')
+    steps:
+      - name: "Checkout"
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: "Download results ⬇️"
+        uses: actions/download-artifact@v4
+        with:
+          path: results
+          merge-multiple: true
+
+      - name: "Download appslist"
+        uses: actions/download-artifact@v4
+        with:
+          name: appslist
+
+      - name: "Git Config"
+        run: |
+          git config --global user.name "${{ github.repository_owner }}"
+          git config --global user.email "noreply@github.com"
+
+      - name: "Process log results"
+        run: |
+          mkdir -p results
           for LogFile in results/out-*; do
             echo '-----------------------------------------------------------------'
             echo "$LogFile out"
@@ -702,6 +751,7 @@ jobs:
           fi
           echo "### 🛅 $remaining to test" >> $GITHUB_STEP_SUMMARY
           rm -f appslist
+          rm -f results/appslist
           rm -f results/ok-*
           echo '-----------------------------------------------------------------'
           echo "Missed results:"
@@ -712,8 +762,16 @@ jobs:
           done
           echo '-----------------------------------------------------------------'
 
+  push:
+    name: "Push"
+    needs: update-results
+    if: (always() && ${{ needs.generate-matrix.outputs.skip != 'true' }})
+    runs-on: ubuntu-22.04
+    steps:
+      - name: "Checkout"
+        uses: actions/checkout@v4
+
       - name: "Push"
-        if: ${{ needs.generate-matrix.outputs.skip != 'true' }}
         run: |
           git config --global user.name "${{ github.repository_owner }}"
           git config --global user.email "noreply@github.com"
